MastodonC/kixi.datastore

src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj

This adds a fdef for error-response in the web-server. This function is
then instrumented in the tests, creating failures if any resource tries
to misuse this function.

Error spec for error responses

---

circle.yml
project.clj
src/kixi/datastore/schemastore.clj
src/kixi/datastore/schemastore/conformers.clj
src/kixi/datastore/schemastore/validator.clj
test/kixi/unit/schemastore/schemastore_test.clj

Adding them there allows them to be actually used.
Expanded the test suite for this massively with a suite of generative
tests that explore the boundaries of our spec elements.

Add new schema types to resolve-spec

---

src/kixi/datastore/metadatastore.clj
src/kixi/datastore/schemastore.clj
src/kixi/datastore/schemastore/conformers.clj
src/kixi/datastore/schemastore/inmemory.clj
src/kixi/datastore/segmentation.clj
src/kixi/datastore/time.clj
src/kixi/datastore/transport_specs.clj
src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/unit/transport_specs_test.clj

Instead of each piece of metadata being defined in a separate part of the multi-part request, there are now only two parts. One for the file, the other for a json encoded map of metadata.
The metadata must conform to the new transport-spec for incoming metadata and it's transposed into the internal format in the transport_specs namespace. Both the internal and external have been modified so that they can be generated, allowing the transposition function to be fdef'd and auto-tested by spec.check.
This allows us to have optional elements in the metadata.

Moved file metadata on upload to a json map

---

src/kixi/datastore/communication_specs.clj
src/kixi/datastore/metadatastore.clj
src/kixi/datastore/metadatastore/inmemory.clj
src/kixi/datastore/metrics.clj
src/kixi/datastore/schemastore/conformers.clj
src/kixi/datastore/segmentation/inmemory.clj
src/kixi/datastore/structural_validation.clj
src/kixi/datastore/transport_specs.clj
src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj
test/kixi/unit/schemastore/conformers_test.clj
test/kixi/unit/schemastore/schemastore_test.clj
test/kixi/unit/transport_specs_test.clj

The file and file-metadata permissions have been defined and added to
the spec's for the file-metadata.
A problem with our uuid spec type has been solved, lack of a call to
conformer to wrap the base definition was causing valid? to see
:clojure.spec/invalid which it interrpretted as true.
Finally solved the problem with metrics having a non-typed call, which
was throwing off the compilation

Sharing permissions for files

---

src/kixi/datastore/metadatastore.clj
src/kixi/datastore/schemastore.clj
src/kixi/datastore/schemastore/conformers.clj
src/kixi/datastore/schemastore/inmemory.clj
src/kixi/datastore/segmentation/inmemory.clj
src/kixi/datastore/sharing.clj
src/kixi/datastore/transport_specs.clj
src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj
test/kixi/integration/segmentation_test.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/spec_test.clj
test/kixi/integration/upload_test.clj
test/kixi/unit/schemastore/schemastore_test.clj
test/kixi/unit/transport_specs_test.clj
test/kixi/unit/web_server_test.clj

The ground layer for schema permissions. These changes allow the :sharing information to be stored within the metadata for the schema.
This involved quite a bit of faffing around:
The schema definitions have been nested with the schema data, instead of being top level.
The file sharing has been consolidated, so that :sharing is a common tag across both entities.
Our internal timestamp schema type has been fixed.
Schemas can now be generated.
List's and primitive schemas have been separated, so you can not have list of list schemas.
Namespaced keyword schema type created.
The schema transform util functions have been moved into the transport-spec namespace.
The whole schema upload section has been refactored.
Lots of little testing functions created and refactored to try and keep the tests …

Schema sharing information stored

---

test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj
test/kixi/integration/segmentation_test.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/spec_test.clj
test/kixi/integration/upload_test.clj

This allows for some partial definitions that clean up some of the tests
a bit.

Moved uid's to be first args for base namespace

---

docker-compose.yml
project.clj
resources/config.edn
src/kixi/datastore/metadatastore/elasticsearch.clj
src/kixi/datastore/system.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj

Migrates the DataStore from inmemory file metadata storage to elastic search.
They'll be more to do here as the type in elastic search will need to be evolved as we extend the metadata. Also all the elements we may wish to query by might not be covered. Will pick that stuff up when the query api get's put together.

ElasticSearch for metadata storage

---

circle.yml
project.clj
resources/config.edn
src/kixi/datastore/elasticsearch.clj
src/kixi/datastore/filestore.clj
src/kixi/datastore/filestore/local.clj
src/kixi/datastore/filestore/s3.clj
src/kixi/datastore/segmentation/inmemory.clj
src/kixi/datastore/system.clj
src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/integration/segmentation_test.clj
test/kixi/integration/upload_test.clj
test/kixi/repl.clj

There is no reliable local S3 implementation at this time, due to the
java sdk being up graded recently to move to chunked upload.
Therefore, when testing locally, by default the s3 layer will not be
used. Need to find a way to get this work correctly on circleci at
least.
There is a bit to be desired around the code at this point. There is no
S3 upload error handling, and the use of a tuple in the return from
output-stream is not very good. Might have to introduce more core.async
to make that clean or just live with this until a better idea occurs.

Implement S3 storage for filestore

---

project.clj

core.spec depends on this, so it's no longer a test only dependancy

Fix test.check dep

---

circle.yml
deployment/marathon-config.json.template
project.clj
resources/config.edn
src/kixi/datastore/elasticsearch.clj
src/kixi/datastore/filestore.clj
src/kixi/datastore/web_server.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj
test/kixi/integration/search/paging_test.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/spec_test.clj
test/kixi/integration/upload_test.clj
test/kixi/repl.clj

We're having trouble with tests seeing other tests events. This change ensures that each test uses it's own uuid, which is used for event detection, hopefully bringing an end to this madnesss.

Modify integration tests to work better with Jenkins

---

src/kixi/datastore/metadatastore/command/handler.clj
src/kixi/datastore/metadatastore/dynamodb.clj
test/kixi/integration/base.clj
test/kixi/integration/dload_test.clj
test/kixi/integration/metadata_update_test.clj
test/kixi/integration/search/ordering_test.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/upload_test.clj

Supplied fields are overwritten completely, there is no partial add or
removal for lists via this method.

Metadata edit

---

src/kixi/datastore/dynamodb.clj
src/kixi/datastore/metadatastore/updates.clj
test/kixi/integration/datapack_update_test.clj
test/kixi/unit/dynamodb_test.clj

Dynamodb doesn't allow multiple updates to the same field in the same
update. The db layer now separates these situations into separate
updates to Dynamo.

Multiple operations on single field supported

---

src/kixi/datastore/metadatastore/command/handler.clj
test/kixi/integration/datapack_update_test.clj

Adding or removing files from bundles is of auditable interest,
therefore they should be in a separate cmd/event, not bundled in with
general metadata updates.
Disabled a test for now until the new command gets made.

Removed packed-ids from update commands

---

docker-compose.yml
src/kixi/datastore/dynamodb.clj
src/kixi/datastore/metadatastore/dynamodb.clj
src/kixi/datastore/schemastore/dynamodb.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_test.clj

Potentially the system could recieve two events to create a single
piece of metadata. The second could over write any and all
information.
Moving the Metadata create step to an insert, with a write condition
that the id doesn't already exist, removes this possibility.

Metadata create moved to insert if not present

---

resources/config.edn
src/kixi/datastore/metadatastore/command/handler.clj
test/kixi/integration/base.clj

A new command is introduced for creating datapacks, however it simply
routes to the current metadata handler as that is capable of handling
all metadatas.
This is just a stepping stone to more cmd/event changes.

Datapacks can be created via create-datapack commands

---

project.clj
test/kixi/acceptance/kaylee_test.clj
test/kixi/integration/datapack_update_test.clj
test/kixi/integration/dload_test.clj
test/kixi/integration/metadata_test.clj
test/kixi/integration/metadata_update_test.clj
test/kixi/integration/schema.clj
test/kixi/integration/search/activity_test.clj
test/kixi/integration/search/ordering_test.clj
test/kixi/integration/search/paging_test.clj
test/kixi/integration/segmentation_test.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/spec_test.clj
test/kixi/integration/upload_test.clj

With the addition of the kaylee tests, we finally have some tests that
can't be run in the staging-jenkins mode. Introduced both :integration
and :acceptance metadata on the test namespaces.

Test namespace metadata to allow for selective test runs

---

project.clj
resources/config.edn
src/kixi/datastore/metadatastore/dynamodb.clj
src/kixi/datastore/system.clj

Up to now the profile has been repeated in several places in the
config, which leads to errors. The system namespace now inserts it
into all the components.

Component profile asigned in consistent manner

---

project.clj

Something appears to have changed in the region lookup area of the
client builders, we are backing on this change until we have some time
to look into it properly.

Downgrading amazonica and aws-java-sdk

---

deployment/Dockerfile

We're making this change so that all microservices are using the same
base image

Change to the prebuilt java8 phusion image

---

resources/config.edn
src/kixi/datastore/filestore.clj
src/kixi/datastore/filestore/command_handler.clj
src/kixi/datastore/filestore/commands.clj
src/kixi/datastore/filestore/events.clj
src/kixi/datastore/filestore/local.clj
src/kixi/datastore/filestore/s3.clj
src/kixi/datastore/filestore/upload.clj
src/kixi/datastore/metadatastore/command_handler.clj
src/kixi/datastore/repl.clj
test/kixi/integration/base.clj
test/kixi/integration/upload_test.clj

In this patch we introduce two new commands - one to begin a
multi-part upload and one to complete it. This will, in time, replace
the existing upload link command.

Add multi-part file uploads via commands/events 

---

deployment/marathon-config.json.template
deployment/production-marathon.json
resources/config.edn
src/kixi/datastore/web_server.clj

This will cause DCOS to actually check the healthcheck path and assert
the web interface is available.

Healthchecks to HTTP from TCP

---

project.clj
src/kixi/datastore/metadatastore/command_handler.clj
src/kixi/datastore/structural_validation.clj
test/kixi/integration/base.clj

Certain handlers weren't providing their partition keys. The new
kixi.comms versions forces even the older event format to explicitly
provide the partition key.
This change moves up to that version and corrects the misbehaving handlers.

Upgrading to partition key forcing kixi.comms

---

project.clj
resources/config.edn
src/kixi/datastore/dynamodb.clj
src/kixi/datastore/filestore.clj
src/kixi/datastore/filestore/command_handler.clj
src/kixi/datastore/filestore/commands.clj
src/kixi/datastore/filestore/events.clj
src/kixi/datastore/filestore/local.clj
src/kixi/datastore/filestore/migrators/dynamodb/migrator_20171109_init.clj
src/kixi/datastore/filestore/s3.clj
src/kixi/datastore/filestore/upload.clj
src/kixi/datastore/filestore/upload_cache/dynamodb.clj
src/kixi/datastore/filestore/upload_cache/inmemory.clj
src/kixi/datastore/metadatastore/dynamodb.clj
src/kixi/datastore/system.clj
test/kixi/integration/base.clj
test/kixi/integration/upload_test.clj
test/kixi/unit/filestore/command_handler.clj

A few changes
* New commands: `initiate-file-upload` and `complete-file-upload`
* New events: `file-upload-initiated`, `file-upload-completed` and `file-upload-rejected`
* Uploads can now only be completed by the user who initiated the upload (otherwise `unauthorised`).
* "Upload IDs" are gone - we only need/use file IDs.
The purpose of the consolidation is to avoid having two separate processes for upload. Previously, once the user had established whether their file is greater-than the minimum size for a multipart upload they would use two entirely separate exchanges. Now there is just one; the juggling of mpu-or-not is handled entirely by the Datastore. This costs us a bit of state which is now handled by DynamoDB.

Consolidate upload commands into one shiny new one

---

src/kixi/datastore/filestore.clj
src/kixi/datastore/filestore/command_handler.clj
src/kixi/datastore/filestore/events.clj
test/kixi/integration/base.clj
test/kixi/integration/upload_test.clj

**Every** command should have a corresponding 'failed to validate' event.

Add `failed` event when a bad command comes through for `initiate-file-upload`

---

src/kixi/datastore/filestore/command_handler.clj
src/kixi/datastore/filestore/event_handler.clj
src/kixi/datastore/filestore/local.clj
src/kixi/datastore/filestore/s3.clj
test/kixi/integration/base.clj

Currently the multi part upload cache is written to when an initate
upload event is consumed by an event handler. This is occuring too late
for quick uploads and they are being failed due to the line not having
been written yet.
This change writes to the mup cache when the command is deemed
successful, therefore the line will already be present before the
upload can possibly be completed.

Moving mup cache to command handler

---

test/kixi/integration/datapack_update_test.clj
test/kixi/integration/metadata_test.clj
test/kixi/integration/metadata_update_test.clj
test/kixi/integration/schema.clj
test/kixi/integration/sharing_test.clj
test/kixi/integration/spec_test.clj

Our test runs againsts staging are taking too long, so we're down
grading a bunch of integration tests to acceptance test, so they are
only run locally.
Generally the tests downgraded are the failure scenarios and close to
over lapping tests.

Downgrading some tests to acceptance

---

dev/user.clj
project.clj
src/kixi/datastore/filestore/command_handler.clj
src/kixi/datastore/filestore/migrators/dynamodb/migrator_20171221_ttl.clj
src/kixi/datastore/filestore/upload.clj
src/kixi/datastore/filestore/upload_cache/dynamodb.clj
src/kixi/datastore/filestore/upload_cache/inmemory.clj
src/kixi/datastore/time.clj

In this PR we add `TTL` to the upload cache table. We have to provide a column which DynamoDB can use to calc TTL which is `kixi.datastore.filestore.upload/ttl` - this is applied to new rows but also retroactively applied to the cache as part of the migration.

Add TTL to rows in upload cache table

---

src/kixi/datastore/filestore/migrators/dynamodb/migrator_20171221_ttl.clj

The `get` expression was using the string, rather than keyword form of the ID column

Fix a bug in the TTL migration code

---

src/kixi/datastore/filestore/migrators/dynamodb/migrator_20171221_ttl.clj

This was breaking the docker version of datastore

Disallow `local-kinesis` profile from executing the TTL migration

---

src/kixi/datastore/dynamodb.clj
src/kixi/datastore/patches/patch_20180111.clj

**A bug in the patch meant the event was not being sent**
Keys being returned from the db were keywords and not strings

A bug in the patch meant the event was not being sent

---

src/kixi/datastore/dynamodb.clj
src/kixi/datastore/metadatastore/dynamodb.clj

Introduces get-item-ignore-tombstone fn at the db layer, so updates to
the sharing matrix can occur for tombstoned items. This was
encountered as part of a patch to extract the bundle-add permission
from meta-update.

Sharing updates allowed for tombstoned items

---

src/kixi/datastore/metadatastore.clj

This reverts commit 7b52a12
We need to keep this a set, and alter kixi spec to respect this. i.e, the other way around.  Else we are effectively creating a new event type.

Revert "fix-up bundled-ids spec"

---

project.clj
src/kixi/datastore/metadatastore.clj
src/kixi/datastore/metadatastore/command_handler.clj
src/kixi/datastore/metadatastore/events.clj
test/kixi/integration/datapack_update_test.clj

**Rejected events use 'relaxed' versions of specs**
In the instance that a command is received and deemed to be invalid,
we cannot simply pass data through; it should be assumed that all data
is garbage, unparse-able etc. In this case, it only makes sense to use
less strict spec when we send out 'rejected' events that typically
reference this data.

Rejected events use 'relaxed' versions of specs

---

src/kixi/datastore/communication_specs.clj
src/kixi/datastore/metadatastore.clj
src/kixi/datastore/metadatastore/command_handler.clj
src/kixi/datastore/metadatastore/commands.clj
src/kixi/datastore/metadatastore/dynamodb.clj
src/kixi/datastore/metadatastore/events.clj
test/kixi/integration/base.clj
test/kixi/integration/metadata_update_test.clj
test/kixi/integration/search/activity_test.clj
test/kixi/integration/sharing_test.clj

* `:kixi.datastore/sharing-change` command (cousin of `:kixi.datastore.metadatastore/sharing-change`)
* `:kixi.datastore/sharing-changed` event (cousin of `:kixi.datastore.file-metadata/updated`)
* `:kixi.datastore/sharing-change-rejected` event (cousin of `:kixi.datastore.metadatastore/sharing-change-rejected`)
As much as possible, the old code paths have been adapted, although very little is needed as the `payload` of the original commands/events is the spec of the new commands/events. Tests have also been added to ensure the old code paths and old commands/events are still working. Until the old commands/events are truly deprecated, there might be parts of the system still using them.

Add new format commands and events for sharing alterations
